import {useEffect,useMemo,useRef,useState} from 'react';
import type {Skin,Selection} from '../lib/types';
import {useLocalState,validIds} from '../lib/local-state';
import {filterSkins} from '../lib/filters';
import {tiers} from '../lib/metadata';
import Art from './Art';
import {winnerAction} from '../lib/roulette-model';
export default function Roulette({skins,selections,guest,onWish,ready}:{skins:Skin[];selections:Record<string,Selection>;guest:boolean;onWish:(s:Skin)=>Promise<void>;ready:boolean}){
 const [custom,setCustom,storageError]=useLocalState<string[]>('skin-vault-viewer-roulette-v2',[],validIds);
 const [source,setSource]=useState(guest?'custom':'owned'),[weapon,setWeapon]=useState('Все'),[rarity,setRarity]=useState('all'),[hideBP,setHideBP]=useState(true),[query,setQuery]=useState(''),[limit,setLimit]=useState(36);
 const [spinning,setSpinning]=useState(false),[winner,setWinner]=useState<Skin|null>(null),[reel,setReel]=useState<Skin[]>([]),[offset,setOffset]=useState(0),[animate,setAnimate]=useState(false),[sound,setSound]=useState(false),[saving,setSaving]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),audio=useRef<AudioContext|null>(null),spinLock=useRef(false);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);void audio.current?.close();},[]);
 const options={tab:guest?'catalog':source,weapon,query:'',rarity,hideBattlepass:hideBP,sort:'featured'};
 const candidates=useMemo(()=>filterSkins(skins,{}, {...options,tab:'catalog',query}),[skins,weapon,rarity,hideBP,query]);
 const pool=filterSkins(skins,selections,options).filter(s=>source!=='custom'||custom.includes(s.id));
 const activeIds=new Set(skins.map(s=>s.id));const count=custom.filter(id=>activeIds.has(id)).length;
 function clearResult(){setWinner(null);setReel([]);setOffset(0);setAnimate(false);}
 function random(n:number){const a=new Uint32Array(1),limit=2**32-(2**32%n);do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%n;}
 function beep(){if(!sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const o=audio.current.createOscillator(),g=audio.current.createGain();o.frequency.value=880;g.gain.setValueAtTime(.04,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.3);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+.3);}catch{}}
 function spin(){if(spinLock.current||!pool.length)return;spinLock.current=true;const win=pool[random(pool.length)];const strip=Array.from({length:36},()=>pool[random(pool.length)]);strip[32]=win;setWinner(null);setSpinning(true);setAnimate(false);setOffset(0);setReel(strip);if(sound){try{audio.current??=new AudioContext();void audio.current.resume();}catch{}}timer.current=setTimeout(()=>{setAnimate(true);setOffset(32*148);timer.current=setTimeout(()=>{setSpinning(false);spinLock.current=false;setWinner(win);beep();},4300);},60);}
 return <section className="roulette-tool"><div className="tool-intro"><div><p className="eyebrow">RANDOM PICK</p><h2>Пусть решит случай.</h2><p className="muted">{guest?'Собери свой набор и выбирай скин для следующей игры.':'Выбирай из своих скинов, вишлиста или всего каталога.'}</p></div><button className="secondary" aria-pressed={sound} onClick={()=>setSound(!sound)}>{sound?'♪ Звук включён':'Звук выключен'}</button></div>
 <div className="roulette panel large"><div className="reel-window"><div className="pointer top"/><div className="pointer bottom"/><div className="reel" style={{transform:`translateX(calc(50% - 69px - ${offset}px))`,transition:animate?'transform 4.3s cubic-bezier(.12,.72,.16,1)':'none'}}>{(reel.length?reel:pool.slice(0,5)).map((s,i)=><div className="reel-tile" key={s.id+i}><Art skin={s}/><span>{s.weapon}</span></div>)}</div>{!pool.length&&<div className="reel-empty">Добавь скины или измени фильтры</div>}<div className="selection-line"/></div>
 <fieldset disabled={spinning} className="tool-toolbar"><label>Выбирать из<select value={source} onChange={e=>{setSource(e.target.value);clearResult();}}>{guest?<option value="custom">Мой набор зрителя</option>:<><option value="owned">Моей коллекции</option><option value="wished">Моего вишлиста</option></>}<option value="catalog">Всего каталога</option></select></label><label>Оружие<select value={weapon} onChange={e=>{setWeapon(e.target.value);setLimit(36);clearResult();}}><option>Все</option>{[...new Set(skins.map(s=>s.weapon))].sort().map(w=><option key={w}>{w}</option>)}</select></label><label>Редкость<select value={rarity} onChange={e=>{setRarity(e.target.value);clearResult();}}><option value="all">Все редкости</option>{tiers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}<option value="none">Без класса</option></select></label><label><input type="checkbox" checked={hideBP} onChange={e=>{setHideBP(e.target.checked);clearResult();}}/> Скрыть БП</label></fieldset><p className="pool-count">Участвует скинов: {pool.length}</p><button className="primary spin-button" disabled={spinning||!pool.length||(!guest&&source!=='catalog'&&!ready)} onClick={spin}>{spinning?'Выбираем скин…':winner?'Крутить ещё':'Крутить рулетку'}</button><div className="result" aria-live="polite">{winner?<><span className="eyebrow">ТВОЙ СКИН</span><strong>{winner.name}</strong>{guest?<span className="muted">{custom.includes(winner.id)?'В твоём наборе':'Случайный выбор из каталога'}</span>:winnerAction(guest,selections[winner.id])==='owned'?<span className="owned-result">✓ Уже в коллекции</span>:<button className="secondary" disabled={saving||!ready||!!selections[winner.id]?.wished} onClick={async()=>{setSaving(true);try{await onWish(winner);}finally{setSaving(false);}}}>{selections[winner.id]?.wished?'♥ Уже в вишлисте':saving?'Сохраняем…':'♡ Добавить в вишлист'}</button>}</>:<p className="muted">Здесь появится твой следующий выбор</p>}</div></div>
 {guest&&<section className="viewer-pool"><div className="catalog-heading"><h2>Мой набор <span className="counter">{count}</span></h2><button className="text-button" disabled={spinning||!custom.length} onClick={()=>{if(confirm('Очистить твой набор рулетки?')){setCustom([]);clearResult();}}}>Очистить набор</button></div><p className="local-note">Отметь свои скины. Набор сохраняется в этом браузере и не меняет коллекцию стримера.</p>{storageError&&<p role="alert">Не удалось сохранить набор в браузере. До закрытия страницы рулетка работает.</p>}<div className="tool-toolbar"><input className="tool-search" placeholder="Найти скин для набора" aria-label="Поиск скинов для рулетки" value={query} onChange={e=>{setQuery(e.target.value);setLimit(36);}}/><button className="secondary" disabled={spinning||!candidates.length} onClick={()=>{setCustom(ids=>[...new Set([...ids,...candidates.map(s=>s.id)])]);clearResult();}}>Добавить найденные ({candidates.length})</button></div><div className="tier-pool-grid">{candidates.slice(0,limit).map(s=><button className={'tier-skin '+(custom.includes(s.id)?'picked':'')} key={s.id} disabled={spinning} aria-pressed={custom.includes(s.id)} onClick={()=>{setCustom(ids=>ids.includes(s.id)?ids.filter(id=>id!==s.id):[...ids,s.id]);clearResult();}}><Art skin={s}/><span>{custom.includes(s.id)?'✓ ':''}{s.name}</span></button>)}</div>{!candidates.length&&<p>Скины не найдены. Попробуй другие фильтры.</p>}{limit<candidates.length&&<button className="secondary more" onClick={()=>setLimit(n=>n+36)}>Показать ещё</button>}</section>}
 </section>;
}
