import {useEffect,useMemo,useRef,useState} from 'react';
import type {Skin} from '../lib/types';
import {useLocalState} from '../lib/local-state';
import {moveSkin,newRows,validBoards,type TierRow,type TierBoards} from '../lib/tier-model';
import {exportTier} from '../lib/tier-export';
import Art from './Art';
import {startDragScroll} from '../lib/drag-scroll';
export default function TierMaker({skins,guest=false}:{skins:Skin[];guest?:boolean}){
 const [boards,setBoards,storageError]=useLocalState<TierBoards>('skin-vault-tiers-v2-'+(guest?'viewer':'owner'),{},validBoards);
 const [template,setTemplate]=useState('Vandal'),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[hideBP,setHideBP]=useState(true),[limit,setLimit]=useState(60),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const stopScroll=useRef<(()=>void)|null>(null);
 useEffect(()=>()=>stopScroll.current?.(),[]);
 function beginDrag(){stopScroll.current?.();stopScroll.current=startDragScroll();}
 function endDrag(){stopScroll.current?.();stopScroll.current=null;}
 const initial=useMemo(()=>newRows(),[template]);const rows=boards[template]??initial;const byId=useMemo(()=>new Map(skins.map(s=>[s.id,s])),[skins]);
 const assigned=new Set(rows.flatMap(r=>r.skins));const pool=skins.filter(s=>(template==='Все'||s.weapon===template)&&!assigned.has(s.id)&&(!hideBP||s.origin!=='battlepass')&&s.name.toLowerCase().includes(query.toLowerCase()));
 function update(fn:(r:TierRow[])=>TierRow[]){setBoards(b=>({...b,[template]:fn(b[template]??initial)}));}
 function place(target:string|null,id=selected,before?:string){if(!id||!byId.has(id))return;update(r=>moveSkin(r,id,target,before));setSelected(null);}
 function changeTemplate(value:string){setTemplate(value);setSelected(null);setQuery('');setLimit(60);setNotice('');}
 async function download(){setBusy(true);setNotice('Готовим картинку…');try{const missing=await exportTier(rows,skins,`Тир-лист · ${template==='Все'?'Всё оружие':template}`);setNotice(missing?`PNG скачан. Для ${missing} скинов сохранены названия без картинок: источник изображений недоступен.`:'Тир-лист скачан в PNG');}catch(e){setNotice(e instanceof Error?e.message:'Ошибка экспорта');}finally{setBusy(false);}}
 return <section className="tier-maker"><div className="tool-intro"><div><p className="eyebrow">ТВОЙ ВКУС — ТВОИ ПРАВИЛА</p><h2>Расставь любимчиков</h2><p className="muted">Перетаскивай скин к краю экрана для прокрутки. Или нажми на скин, прокрути страницу и выбери ряд. Для точного места нажми на другой скин в ряду.</p></div><button className="primary" disabled={busy||!assigned.size} onClick={download}>{busy?'Готовим PNG…':'↓ Скачать PNG'}</button></div>
 <div className="tool-toolbar"><div className="chips">{['Vandal','Phantom','Ножи','Все'].map(w=><button key={w} className={template===w?'active':''} onClick={()=>changeTemplate(w)}>{w==='Все'?'Всё оружие':w}</button>)}</div><label>Шаблон<select value={template} onChange={e=>changeTemplate(e.target.value)}><option value="Все">Всё оружие</option>{[...new Set(skins.map(s=>s.weapon))].sort().map(w=><option key={w}>{w}</option>)}</select></label></div>
 <p className="local-note">Твои тир-листы сохраняются только в этом браузере. У каждого шаблона свой черновик.</p>{storageError&&<p role="alert">Браузер запрещает сохранение. Скачай PNG перед закрытием страницы.</p>}
 {selected&&<div className="placement-bar" role="status">Выбран: {byId.get(selected)?.name}<button onClick={()=>setSelected(null)}>Отменить</button><button onClick={()=>place(null)}>Вернуть в набор</button></div>}
 <div className="tier-board">{rows.map((row,index)=><section className="tier-row" key={row.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(row.id,e.dataTransfer.getData('text/plain'));}}><div className="tier-label" style={{background:row.color}}><input aria-label={`Название ряда ${index+1}`} maxLength={24} value={row.label} onChange={e=>update(rs=>rs.map(r=>r.id===row.id?{...r,label:e.target.value}:r))}/><div className="tier-row-tools"><input type="color" aria-label={`Цвет ряда ${index+1}`} value={row.color} onChange={e=>update(rs=>rs.map(r=>r.id===row.id?{...r,color:e.target.value}:r))}/><button aria-label={`Поднять ряд ${row.label}`} disabled={index===0} onClick={()=>update(rs=>{const n=[...rs];[n[index-1],n[index]]=[n[index],n[index-1]];return n;})}>↑</button><button aria-label={`Опустить ряд ${row.label}`} disabled={index===rows.length-1} onClick={()=>update(rs=>{const n=[...rs];[n[index+1],n[index]]=[n[index],n[index+1]];return n;})}>↓</button><button aria-label={`Удалить ряд ${row.label} и вернуть скины в набор`} disabled={rows.length===1} onClick={()=>update(rs=>rs.filter(r=>r.id!==row.id))}>×</button></div></div><div className="tier-slots">{row.skins.map(id=>{const s=byId.get(id);return <button draggable key={id} title={s?.name??id} className={'tier-skin '+(selected===id?'picked':'')} onDragStart={e=>{beginDrag();e.dataTransfer.setData('text/plain',id);setSelected(id);}} onDragEnd={endDrag} onDrop={e=>{e.preventDefault();e.stopPropagation();place(row.id,e.dataTransfer.getData('text/plain'),id);}} onClick={()=>selected&&selected!==id?place(row.id,selected,id):setSelected(selected===id?null:id)}>{s?<><Art skin={s}/><span>{s.name}</span></>:<span>Скин недоступен</span>}</button>})}<button className="tier-drop" onClick={()=>selected?place(row.id):setNotice('Сначала выбери скин из набора ниже')} aria-label={`Поместить выбранный скин в ${row.label}`}>{row.skins.length?'＋':'Помести скин сюда'}</button></div></section>)}</div>
 <div className="tool-toolbar"><button className="secondary" disabled={rows.length>=30} onClick={()=>update(rs=>[...rs,{id:crypto.randomUUID(),label:'Новый',color:'#c9a5ef',skins:[]}])}>＋ Добавить ряд</button><button className="text-button" onClick={()=>{if(confirm('Вернуть все скины этого шаблона в набор?')){update(rs=>rs.map(r=>({...r,skins:[]})));setSelected(null);}}}>Очистить размещение</button></div>
 {notice&&<p className="tool-notice" role="status">{notice}</p>}
 <div className="tier-pool" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(null,e.dataTransfer.getData('text/plain'));}}><div className="catalog-heading"><h3>Скины для распределения <span className="counter">{pool.length}</span></h3><button className="secondary" disabled={!selected} onClick={()=>place(null)}>Вернуть выбранный</button></div><div className="tool-toolbar"><input className="tool-search" placeholder="Поиск скина" aria-label="Поиск скинов для тир-листа" value={query} onChange={e=>{setQuery(e.target.value);setLimit(60);}}/><label><input type="checkbox" checked={hideBP} onChange={e=>{setHideBP(e.target.checked);setLimit(60);}}/> Скрыть БП в наборе</label></div><div className="tier-pool-grid">{pool.slice(0,limit).map(s=><button draggable key={s.id} className={'tier-skin '+(selected===s.id?'picked':'')} aria-pressed={selected===s.id} onDragStart={e=>{beginDrag();e.dataTransfer.setData('text/plain',s.id);setSelected(s.id);}} onDragEnd={endDrag} onClick={()=>setSelected(selected===s.id?null:s.id)}><Art skin={s}/><span>{s.name}</span></button>)}</div>{!pool.length&&<p className="muted">Здесь больше нет скинов под выбранные фильтры.</p>}{limit<pool.length&&<button className="secondary more" onClick={()=>setLimit(x=>x+60)}>Показать ещё</button>}</div></section>;
}
