import { apiRequest } from './lib/api';
import { guestUrl } from './lib/config';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Check, CheckCheck, ChevronDown, Crosshair, Grid2X2, Heart, LoaderCircle, RefreshCw, Search, Sparkles, Link2, Pencil, Volume2, VolumeX, X } from 'lucide-react';
import snapshot from './lib/catalog-snapshot.json';
import type { Catalog, Selection, Skin } from './lib/types';
import { tiers,priceLabel } from './lib/metadata';
import { filterSkins,effectivePrice } from './lib/filters';
type Tab='catalog'|'owned'|'wished'|'roulette';
const baseLabels:Record<Tab,string>={catalog:'Каталог',owned:'Моя коллекция',wished:'Вишлист',roulette:'Рулетка'};
const preferred=['Vandal','Phantom','Ножи','Sheriff','Operator','Ghost'];
function rank(s:Skin){let v=preferred.indexOf(s.weapon);return (v<0?20:v)*100+(/Жнец|Прайм|Ионизация|Аракс|Куронами|Прелюдия|Reaver|Prime|Kuronami/i.test(s.name)?0:50);}
function randomIndex(n:number){const x=new Uint32Array(1);const limit=4294967296-4294967296%n;do{crypto.getRandomValues(x);}while(x[0]>=limit);return x[0]%n;}
function Art({skin}:{skin:Skin}){const [failed,setFailed]=useState(false);return failed?<div className="image-fallback"><Crosshair size={36}/><span>{skin.weapon}</span></div>:<img src={skin.image} alt={skin.name} loading="lazy" onError={()=>setFailed(true)}/>;}
export default function Home({guest=false}:{guest?:boolean}){
 const labels={...baseLabels,owned:guest?"Коллекция":"Моя коллекция"};
 const [rarity,setRarity]=useState("all"),[hideBattlepass,setHideBattlepass]=useState(true);
 const [editPrice,setEditPrice]=useState<Skin|null>(null),[priceInput,setPriceInput]=useState(""),[priceError,setPriceError]=useState("");
 const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(editPrice)dialogRef.current?.showModal();else dialogRef.current?.close();},[editPrice]);
 const [catalog,setCatalog]=useState<Catalog>(guest?{skins:[],updatedAt:snapshot.updatedAt}:snapshot as Catalog);
 const [selections,setSelections]=useState<Record<string,Selection>>({});
 const [ready,setReady]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const [tab,setTab]=useState<Tab>(guest?'owned':'catalog'),[query,setQuery]=useState(''),[weapon,setWeapon]=useState('Все'),[sort,setSort]=useState('featured'),[limit,setLimit]=useState(30);
 const [notice,setNotice]=useState(''),[loadError,setLoadError]=useState(''),[saving,setSaving]=useState<string[]>([]);
 const [source,setSource]=useState<'catalog'|'owned'|'wished'>('catalog'),[rouletteWeapon,setRouletteWeapon]=useState('Все');
 const [spinning,setSpinning]=useState(false),[reel,setReel]=useState<Skin[]>([]),[offset,setOffset]=useState(0),[animate,setAnimate]=useState(false),[winner,setWinner]=useState<Skin|null>(null);
 const [sound,setSound]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null), audio=useRef<AudioContext|null>(null);
 const lock=useRef(new Set<string>());
 async function loadCollection(){setLoading(true);setLoadError('');try{const r=await apiRequest(guest?'/api/public':'/api/collection');const x=await r.json() as {error:string;selections:Selection[];catalog?:Catalog};if(!r.ok)throw new Error(x.error);if(guest&&x.catalog)setCatalog(x.catalog);setSelections(Object.fromEntries(x.selections.map((s:Selection)=>[s.skinId,s])));setReady(true);}catch(e){setLoadError(e instanceof Error?e.message:'Не удалось загрузить коллекцию');}finally{setLoading(false);}}
 async function refresh(force=false){if(force)setRefreshing(true);try{const r=await apiRequest('/api/catalog'+(force?'?refresh=1':''));const x=await r.json() as Catalog & {error:string};if(!r.ok)throw new Error(x.error);setCatalog(x);if(force)setNotice(x.notice||'Каталог актуален');}catch(e){if(force)setNotice(e instanceof Error?e.message:'Не удалось обновить каталог');}finally{setRefreshing(false);}}
 useEffect(()=>{loadCollection();if(!guest)refresh();return()=>{if(timer.current)clearTimeout(timer.current);audio.current?.close();};},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>setLimit(30),[tab,weapon,query,sort,rarity,hideBattlepass]);
 const all=useMemo(()=>[...catalog.skins].sort((a,b)=>rank(a)-rank(b)||a.name.localeCompare(b.name,'ru')), [catalog]);
 const weapons=useMemo(()=>['Все',...preferred,...Array.from(new Set(all.map(s=>s.weapon))).filter(w=>!preferred.includes(w)).sort()], [all]);
 const owned=all.filter(s=>selections[s.id]?.owned), wished=all.filter(s=>selections[s.id]?.wished);
 const wishedPreview=filterSkins(wished,selections,{tab:"wished",weapon:"Все",query:"",rarity,hideBattlepass,sort:"featured"});
 const filtered=useMemo(()=>filterSkins(all,selections,{tab,weapon,query,rarity,hideBattlepass,sort}),[all,selections,tab,weapon,query,sort,rarity,hideBattlepass]);
 const pool=filterSkins(all,selections,{tab:source,weapon:rouletteWeapon,query:'',rarity,hideBattlepass,sort:'featured'});
 const priceSum=filtered.reduce((total,s)=>total+(effectivePrice(s,selections[s.id])??0),0);
 const missingPrices=filtered.filter(s=>!['battlepass','agent','event'].includes(s.origin)&&effectivePrice(s,selections[s.id])===null).length;
 function openPrice(s:Skin){setEditPrice(s);setPriceInput(String(selections[s.id]?.priceOverride??s.price??''));setPriceError('');}
 async function savePrice(reset=false){if(!editPrice||guest||lock.current.has(editPrice.id))return;const id=editPrice.id;const price=reset?null:Number(priceInput);if(!reset&&(!priceInput.trim()||!Number.isInteger(price)||price!<0||price!>100000)){setPriceError('Укажи целое число от 0 до 100 000');return;}lock.current.add(id);setSaving(p=>[...p,id]);try{const r=await apiRequest('/api/prices',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({skinId:id,price})});const x=await r.json() as {error:string};if(!r.ok)throw new Error(x.error);setSelections(p=>({...p,[id]:{...(p[id]??{skinId:id,owned:false,wished:false}),priceOverride:price}}));setEditPrice(null);setNotice(reset?'Цена из каталога восстановлена':'Цена сохранена');}catch(e){setPriceError(e instanceof Error?e.message:'Не удалось сохранить цену');}finally{lock.current.delete(id);setSaving(p=>p.filter(x=>x!==id));}}
 async function copyGuestLink(){const url=guestUrl();try{await navigator.clipboard.writeText(url);setNotice('Гостевая ссылка скопирована');}catch{setNotice(url);}}
 async function toggle(s:Skin,field:'owned'|'wished'){
  if(guest)return;if(!ready){setNotice('Сначала нужно загрузить коллекцию');return;}if(lock.current.has(s.id))return;
  lock.current.add(s.id);setSaving(p=>[...p,s.id]);
  const old=selections[s.id]||{skinId:s.id,owned:false,wished:false};const next={...old,[field]:!old[field]};
  try{const r=await apiRequest('/api/collection',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const x=await r.json() as {error:string;selections:Selection[]};if(!r.ok)throw new Error(x.error);setSelections(p=>({...p,[s.id]:next}));setNotice(field==='owned'?(next.owned?'Добавлено в коллекцию':'Убрано из коллекции'):(next.wished?'Добавлено в вишлист':'Убрано из вишлиста'));}catch(e){setNotice(e instanceof Error?e.message:'Не удалось сохранить');}finally{lock.current.delete(s.id);setSaving(p=>p.filter(id=>id!==s.id));}
 }
 function beep(){if(!sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const o=audio.current.createOscillator(),g=audio.current.createGain();o.type='sine';o.frequency.setValueAtTime(660,audio.current.currentTime);o.frequency.exponentialRampToValueAtTime(990,audio.current.currentTime+.18);g.gain.setValueAtTime(.06,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.4);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+.4);}catch{}}
 function spin(){if(spinning||!pool.length)return;const win=pool[randomIndex(pool.length)];const strip=Array.from({length:36},()=>pool[randomIndex(pool.length)]);strip[32]=win;setWinner(null);setSpinning(true);setAnimate(false);setOffset(0);setReel(strip);if(sound){try{audio.current??=new AudioContext();void audio.current.resume();}catch{}}
 timer.current=setTimeout(()=>{setAnimate(true);setOffset(32*148);timer.current=setTimeout(()=>{setSpinning(false);setWinner(win);beep();},4300);},60);
 }
 function go(t:Tab){setTab(t);setQuery('');setWeapon('Все');}
 const displayReel=reel.length?reel:pool.slice(0,5);
 const roulette=<section className={'roulette panel '+(tab==='roulette'?'large':'')} aria-label="Рулетка скинов">
  <div className="section-label"><span><Crosshair size={18}/> RANDOM PICK</span><button className="icon-button" aria-label={sound?'Выключить звук':'Включить звук'} aria-pressed={sound} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div>
  <h2>Пусть решит случай<span className="accent">.</span></h2><p className="muted">Один клик. Один скин. Твой следующий выбор.</p>
  <div className="reel-window"><div className="pointer top"/><div className="pointer bottom"/><div className="reel" style={{transform:`translateX(calc(50% - 69px - ${offset}px))`,transition:animate?'transform 4.3s cubic-bezier(.12,.72,.16,1)':'none'}}>{displayReel.map((s,i)=><div className="reel-tile" key={s.id+'-'+i}><Art skin={s}/><span>{s.weapon}</span></div>)}</div>{!pool.length&&!spinning&&<div className="reel-empty">В этом списке пока нет скинов</div>}<div className="selection-line"/></div>
  <div className="roulette-controls"><label>Выбирать из<select value={source} disabled={spinning} onChange={e=>{setSource(e.target.value as typeof source);setReel([]);setWinner(null);setOffset(0);}}><option value="catalog">Всего каталога</option><option value="owned">Моей коллекции</option><option value="wished">Вишлиста</option></select></label><label>Оружие<select value={rouletteWeapon} disabled={spinning} onChange={e=>{setRouletteWeapon(e.target.value);setReel([]);setWinner(null);setOffset(0);}}>{weapons.map(w=><option key={w}>{w}</option>)}</select></label></div>
  <div className="pool-count">{pool.length} скинов участвует</div><button className="primary spin-button" disabled={spinning||!pool.length||(source!=='catalog'&&!ready)} onClick={spin}>{spinning?<LoaderCircle className="rotate" size={20}/>:<RefreshCw size={20}/>} {spinning?'Выбираем скин…':'Крутить рулетку'}</button>
  <div className="result" aria-live="polite">{winner?<><span className="eyebrow">ТВОЙ СКИН</span><strong>{winner.name}</strong>{!guest&&<button className={'text-button '+(selections[winner.id]?.wished?'selected':'')} disabled={!ready||saving.includes(winner.id)} onClick={()=>toggle(winner,'wished')}><Heart size={16} fill={selections[winner.id]?.wished?'currentColor':'none'}/>{selections[winner.id]?.wished?'В вишлисте':'В вишлист'}</button>}</>:<span className="muted">{pool.length?'Результат появится здесь':'Добавь скины или выбери другой список'}</span>}</div>
 </section>;
 return <div className="app-shell"><header className="site-header"><button className="brand" onClick={()=>go(guest?'owned':'catalog')} aria-label="Skin Vault — каталог"><span className="brand-mark">V</span><span>SKIN VAULT<small>VALORANT COLLECTION</small></span></button><nav aria-label="Разделы">{((guest?['owned','wished']:['catalog','owned','wished','roulette']) as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>go(t)}>{t==='catalog'?<Grid2X2 size={18}/>:t==='owned'?<CheckCheck size={18}/>:t==='wished'?<Heart size={18}/>:<Crosshair size={18}/>}<span>{labels[t]}</span></button>)}</nav><span className="header-note">{guest?<>Только просмотр</>:<><Sparkles size={16}/> Режим владельца</>}</span></header>
 <main><div className="page-heading"><div><p className="eyebrow">{guest?"КОЛЛЕКЦИЯ СТРИМЕРА":"ТВОЙ АРСЕНАЛ"}</p><h1>{tab==='catalog'?'Каждый скин — свой вайб.':labels[tab]}<span className="accent">{tab==='catalog'?'':' .'}</span></h1><p className="muted">{tab==='catalog'?'Находи любимые. Собирай коллекцию. Выбирай случайно.':tab==='owned'?(guest?'Скины из коллекции. Цены указаны без скидок и улучшений.':'Все скины, которые ты отметила как свои.'):tab==='wished'?(guest?'Здесь можно посмотреть желаемые скины.':'Скины, которые хочется добавить в свой арсенал.'):'Выбери список — и доверь выбор рулетке.'}</p></div>{!guest&&<button className="secondary refresh-button" onClick={()=>refresh(true)} disabled={refreshing}><RefreshCw size={17} className={refreshing?'rotate':''}/>{refreshing?'Обновляем…':'Обновить каталог'}</button>}</div>
 {!guest&&<div className="sharing-bar"><div><Link2 size={19}/><span><strong>Ссылка для зрителей</strong><small>Коллекция и вишлист · без редактирования</small></span></div><a href={guestUrl()} target="_blank" rel="noreferrer">Открыть гостевой режим</a><button className="secondary" onClick={copyGuestLink}>Скопировать ссылку</button></div>}
 <div className={"stats "+(guest?"guest-stats":"")}><button hidden={guest} onClick={()=>go('catalog')} className={tab==='catalog'?'current':''}><Grid2X2 size={21}/><span>В каталоге<strong>{all.length.toLocaleString('ru-RU')}</strong></span><small>СКИНОВ</small></button><button onClick={()=>go('owned')} className={tab==='owned'?'current':''}><CheckCheck size={21}/><span>{labels.owned}<strong>{ready?owned.length:'—'}</strong></span><small>СОБРАНО</small></button><button onClick={()=>go('wished')} className={tab==='wished'?'current':''}><Heart size={21}/><span>Вишлист<strong>{ready?wished.length:'—'}</strong></span><small>ХОЧУ</small></button></div>
 {loadError&&<div className="error-banner" role="alert">{loadError}<button onClick={loadCollection}>Повторить загрузку</button></div>}
 {catalog.stale&&<div className="error-banner">{catalog.notice}</div>}
 <div className={'workspace '+(tab==='roulette'?'roulette-view':'')}>
 {tab!=='roulette'?<section className="catalog-section"><div className="catalog-heading"><h2>{labels[tab]}<span className="counter">{filtered.length}</span></h2><label className="sort-label"><span className="sr-only">Сортировка</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Популярные серии первыми</option><option value="name">По названию</option><option value="price-low">Цена: по возрастанию</option><option value="price-high">Цена: по убыванию</option><option value="rarity">По редкости</option></select></label></div><div className="filterbar"><label className="search"><Search size={19}/><input placeholder="Найти скин или коллекцию" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Поиск скинов"/>{query&&<button aria-label="Очистить поиск" onClick={()=>setQuery('')}><X size={16}/></button>}</label><label className="weapon-select"><span className="sr-only">Оружие</span><select value={weapon} onChange={e=>setWeapon(e.target.value)}>{weapons.map(w=><option key={w}>{w}</option>)}</select></label></div><div className="extra-filters"><label className="rarity-select"><span>Редкость коллекции</span><select aria-label="Редкость коллекции" value={rarity} onChange={e=>setRarity(e.target.value)}><option value="all">Все редкости</option>{tiers.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}<option value="none">Без класса</option></select></label><label className="bp-checkbox"><input type="checkbox" checked={hideBattlepass} onChange={e=>setHideBattlepass(e.target.checked)}/> Скрыть скины из БП</label></div><div className="chips">{['Все','Vandal','Phantom','Ножи','Sheriff','Operator'].map(w=><button className={weapon===w?'active':''} key={w} onClick={()=>setWeapon(w)}>{w}</button>)}</div>
 {(tab==='owned'||tab==='wished')&&<div className="price-summary"><span>Стоимость показанных скинов</span><strong>{priceSum.toLocaleString('ru-RU')} VP</strong>{missingPrices>0&&<small>Не включено: {missingPrices} без цены</small>}<small>Скины БП, агентов и событий не продаются по отдельности</small></div>}
 {loading&&tab!=='catalog'?<div className="empty"><LoaderCircle className="rotate"/><h3>Загружаем твою коллекцию…</h3></div>:filtered.length?<><div className="skin-grid">{filtered.slice(0,limit).map((s,i)=><article className={'skin-card tone-'+i%6} key={s.id}><div className="card-art"><span className="weapon-watermark" aria-hidden="true">{s.weapon==='Ножи'?'MELEE':s.weapon}</span><Art skin={s}/>{!guest&&<button className={'heart-button '+(selections[s.id]?.wished?'selected':'')} aria-label={(selections[s.id]?.wished?'Убрать из вишлиста: ':'В вишлист: ')+s.name} aria-pressed={!!selections[s.id]?.wished} disabled={!ready||saving.includes(s.id)} onClick={()=>toggle(s,'wished')}><Heart size={20} fill={selections[s.id]?.wished?'currentColor':'none'}/></button>}</div><div className="card-info"><div className="card-meta"><span className="weapon-label">{s.weapon}</span><span className="tier-badge" style={{color:tiers.find(t=>t.id===s.tier)?.color}}>{tiers.find(t=>t.id===s.tier)?.name??"Без класса"}</span></div><h3>{s.name}</h3><div className="skin-price">{!guest&&!["battlepass","agent","event"].includes(s.origin)?<button aria-label={"Изменить цену: "+s.name} onClick={()=>openPrice(s)} disabled={!ready||saving.includes(s.id)}>{priceLabel(s,selections[s.id]?.priceOverride)}<Pencil size={12}/></button>:<span>{priceLabel(s,selections[s.id]?.priceOverride)}</span>}</div>{!guest?<button className={'own-button '+(selections[s.id]?.owned?'owned':'')} disabled={!ready||saving.includes(s.id)} aria-pressed={!!selections[s.id]?.owned} onClick={()=>toggle(s,'owned')}>{saving.includes(s.id)?<LoaderCircle size={15} className="rotate"/>:<Check size={15}/>} {selections[s.id]?.owned?'В коллекции':'Есть у меня'}</button>:<div className="guest-status">{tab==='owned'?<><Check size={14}/>В коллекции</>:<><Heart size={14}/>В вишлисте</>}</div>}</div></article>)}</div>{limit<filtered.length&&<button className="secondary more" onClick={()=>setLimit(n=>n+30)}>Показать ещё · {Math.min(30,filtered.length-limit)} скинов<ChevronDown size={18}/></button>}<p className="shown-count">Показано {Math.min(limit,filtered.length)} из {filtered.length}</p></>:<div className="empty">{tab==='wished'?<Heart size={35}/>:tab==='owned'?<Grid2X2 size={35}/>:<Search size={35}/>}<h3>{query||weapon!=='Все'||rarity!=='all'?'Скины не найдены':tab==='owned'?'Твоя коллекция начинается здесь':'Сохрани то, что нравится'}</h3><p>{query||weapon!=='Все'||rarity!=='all'?'Попробуй другой запрос или оружие.':guest?'В этом списке пока нет скинов.':tab==='owned'?'В каталоге нажми «Есть у меня» на своих скинах.':'Нажми на сердечко у скина в каталоге.'}</p><button className="secondary" onClick={()=>{setQuery('');setWeapon('Все');setRarity('all');setHideBattlepass(false);if(!guest)go('catalog');}}> {guest?'Сбросить фильтры':'Открыть каталог'}</button></div>}</section>:roulette}
 <aside>{!guest&&tab!=='roulette'&&roulette}{guest&&<section className="panel guest-info"><Crosshair size={23}/><h2>Коллекция открыта</h2><p>Посмотри скины и вишлист. Используй поиск, сортировку и фильтры.</p><span>Изменять списки может только владелец.</span></section>}<section className="wishlist-preview panel"><div className="catalog-heading"><h2><Heart size={19}/> Вишлист</h2><button className="icon-button" onClick={()=>go('wished')} aria-label="Открыть вишлист"><ArrowUpRight size={19}/></button></div>{wishedPreview.length?<div className="wishlist-items">{wishedPreview.slice(0,3).map(s=><div className="wishlist-item" key={s.id}><Art skin={s}/><div><span className="weapon-label">{s.weapon}</span><strong>{s.name}</strong><span className="preview-price">{priceLabel(s,selections[s.id]?.priceOverride)}</span></div>{!guest&&<button className="icon-button" disabled={saving.includes(s.id)} aria-label={'Убрать из вишлиста '+s.name} onClick={()=>toggle(s,'wished')}><X size={16}/></button>}</div>)}</div>:<div className="wishlist-empty"><Heart size={27}/><p>Для будущих любимчиков</p><span>{guest?"Здесь появятся желаемые скины владельца.":"Отмечай сердечком скины, которые хочешь."}</span></div>}</section><div className="save-note"><CheckCheck size={17}/><span>{ready?(guest?'Обновления владельца видны после загрузки страницы':'Коллекция и вишлист сохраняются автоматически'):loading?'Загружаем сохранённые скины…':'Коллекция временно недоступна'}</span></div></aside></div>
 <footer><span className="footer-brand">SKIN VAULT</span><span>Каталог: {new Date(catalog.updatedAt).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})} МСК</span><a href="https://valorant-api.com/" target="_blank" rel="noreferrer">Данные Valorant-API</a><span>Не связан с Riot Games. Цены справочные, без скидок, улучшений и комплектов. Цены ножей и отдельных серий могут требовать уточнения.</span></footer>
 </main><dialog ref={dialogRef} className="price-dialog" onCancel={()=>setEditPrice(null)}><form onSubmit={e=>{e.preventDefault();void savePrice();}}><div className="catalog-heading"><h2>Цена скина</h2><button type="button" className="icon-button" aria-label="Закрыть" onClick={()=>setEditPrice(null)}><X size={20}/></button></div><p>{editPrice?.name}</p><label>Цена без скидок, VP<input autoFocus type="number" min="0" max="100000" step="1" value={priceInput} onChange={e=>setPriceInput(e.target.value)} required/></label><small>Укажи подтверждённую цену. Она будет видна зрителям.</small>{priceError&&<p role="alert" className="dialog-error">{priceError}</p>}<div className="dialog-actions"><button type="submit" className="primary" disabled={!!editPrice&&saving.includes(editPrice.id)}>Сохранить</button><button type="button" className="secondary" disabled={!!editPrice&&saving.includes(editPrice.id)} onClick={()=>savePrice(true)}>Вернуть цену каталога</button></div></form></dialog>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Закрыть уведомление" onClick={()=>setNotice('')}><X size={16}/></button></div>}</div>;
}
